# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(default='Test', max_length=30, verbose_name='affiliation'),
            preserve_default=False,
        ),
    ]
